### PR TITLE
Clean-up AES C code

### PR DESCRIPTION
**Pull request by tbeu**
to give no more complaints at [FlexeLint](http://www.gimpel.com/html/index.htm)

### CODE REVIEW

**Comment by chrishulbert** [comment]
Looks really good! But, are you using this for real purposes? This is just an example of how aes works, its not proper

**Comment by tbeu** [comment]
Oh, yes I do. Successfully tested encrpytion/decryption and compared with other implementations.

**Comment by chrishulbert** [comment]
Hi,
I only wrote this code as an exercise in how AES works, it hasn't been
verified formally as secure, and i wouldn't recommend you use it for
anything important. Use it at your own risk i'd say.
Having said that, i'll merge your stuff, looks good.
Cheers

**Comment by tbeu** [comment]
Thanks for merge and code. And yes I am aware of use at own risk. No problem at my side.

**Comment by chrishulbert** [comment]
:P)

**Comment by chrishulbert** [comment]
Oops, i meant:
:)

**Pull request merged**
